# Global Mysql、Redis and RabbitMQ connect configuration items
common:
  rabbitmq:
    password: studio_123456
    port: 15672
  redis:
    host: 16gmaster
    password: studio_123456
    port: 13790
  mysql:
    primary:
      username: root
      password: studio_123456
      url: jdbc:mysql://16gmaster:33060/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    master:
      username: root
      password: studio_123456
      url: jdbc:p6spy:mysql://16gmaster:33060/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    flowable:
      username: root
      password: studio_123456
      url: jdbc:mysql://16gmaster:33060/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    quartz:
      username: root
      password: studio_123456
      url: jdbc:mysql://16gmaster:33060/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
